VCUE-175: Breakdown spack-install-helper into smaller pieces
eth-cscs/ci-ext-base-containers pull request #1
Opened 2023-12-02 10:27 UTC by rjanalik

2023-12-04 10:27 UTC, finkandreas requested changes
Installing the files is missing, I guess having all in `/usr/local/bin` would be fine.

2023-12-04 10:27 UTC, finkandreas commented on bin/spack-install-helper
> +. spack-install-helper-10-preprocessing
Could you replace `.` with `source`. It's easy to miss the dot.

2023-12-04 10:27 UTC, finkandreas commented on bin/spack-install-helper-20-configure-environment
> +cat - > /dev/shm/enforce_microarchitecture.yaml << EOF
Should we write this to a helper file, and copy, instead of writing it?
Not sure what is easier to maintain. Maybe having the content here explicitly is easier for maintenance.
I will let you decide what you would consider easier for the futuere.

2023-12-04 10:30 UTC, rjanalik commented on bin/spack-install-helper-20-configure-environment
> +cat - > /dev/shm/enforce_microarchitecture.yaml << EOF
I was already thinking about this. I agree with you, it is more obvious the way you did it. And also it is just a few lines. So I would keep it as it is.

2023-12-04 10:32 UTC, rjanalik commented on bin/spack-install-helper
> +. spack-install-helper-10-preprocessing
Done

2023-12-05 18:58 UTC, finkandreas approved these changes
LGTM

2023-12-05 18:59 UTC, merged