CI pipeline that builds and tests the base images
eth-cscs/ci-ext-base-containers pull request #11
Opened 2024-05-21 08:50 UTC by rjanalik

2024-05-27 07:03 UTC, finkandreas requested changes

2024-05-27 07:03 UTC, finkandreas commented on ci/ci-generator.py
> +#!/usr/local/bin/python
Could we change this to `#!/usr/bin/env python`, then it runs also on systems that do not have python in `/usr/local/bin`?

2024-05-27 07:03 UTC, finkandreas commented on ci/ci-generator.py
> +    elif target == "cuda":
how does this map to `alps-gh200`?

2024-05-27 07:03 UTC, finkandreas commented on ci/ci-generator.py
> +        spack_target = "alps-mi200"
How will this map to `alps-mi300` in the future?

2024-05-27 07:03 UTC, finkandreas commented on ci/cscs.yml
> +  image: docker.io/rjanalik/ci-generator:python-3.12.3
It's fine to use this image, but could you add the Dockerfile to this repository, so I could be understood what is inside?

2024-05-27 13:35 UTC, rjanalik commented on ci/ci-generator.py
> +    elif target == "cuda":
I split `cuda` to `cuda-x86_64` and `cuda-aarch64`.

2024-05-27 13:39 UTC, rjanalik commented on ci/ci-generator.py
> +        spack_target = "alps-mi200"
The `spack_target` is needed only for tests. I think we can think about this once we have some `mi300`s. Then I could deal with `rocm` the same way as I do now with `cuda`, split it in more targets.

2024-05-29 09:50 UTC, finkandreas reviewed
Some suggestion for better consistency for `CI_GENERATOR_IMAGE_NAME`

2024-05-29 09:50 UTC, finkandreas commented on ci/cscs.yml
> +  CI_GENERATOR_IMAGE_NAME: $CSCS_REGISTRY_PATH/public/ci-generator:$CI_GENERATOR_TAG
I would suggest to have this `CI_GENERATOR_IMAGE_NAME: $CSCS_REGISTRY_PATH/public/ci-generator`

2024-05-29 09:50 UTC, finkandreas commented on ci/cscs.yml
> +    - export PERSIST_IMAGE_NAME=$CSCS_REGISTRY_PATH/public/ci-generator:$CI_GENERATOR_TAG
with the above change this would be `PERSIST_IMAGE_NAME=$CI_GENERATOR_IMAGE_NAME:$CI_GENERATOR_TAG`

2024-05-29 09:50 UTC, finkandreas commented on ci/cscs.yml
> +    PERSIST_IMAGE_NAME: $CI_GENERATOR_IMAGE_NAME
`PERSIST_IMAGE_NAME: $CI_GENERATOR_IMAGE_NAME` is useless, it's overwritten in the `before_script` anyway.

2024-05-29 09:50 UTC, finkandreas commented on ci/cscs.yml
> +  image: $CI_GENERATOR_IMAGE_NAME
with above suggestion this would be `$CI_GENERATOR_IMAGE_NAME:$CI_GENERATOR_TAG`

2024-05-29 09:50 UTC, finkandreas commented on ci/cscs.yml
> +    DOCKERFILE: ci/docker/Dockerfile
maybe `ci/docker/Dockerfile.ci-generator`?

2024-08-07 14:05 UTC, finkandreas approved these changes
LGTM

2024-08-07 14:06 UTC, merged