Multi arch
eth-cscs/ci-ext-base-containers pull request #3
Opened 2024-02-07 14:46 UTC by finkandreas

This PR adds supports for multi-arch support.
We can build the containers on GH nodes, and on x86_64 nodes. They first get tagged with the appropriate architecture.
Then there is an additional script, that combines the two architecture specific images into a single manifest.
Effectively this would work on both an ARM machine and a x86_64 machine:
```
podman pull finkandreas/spack:0.20.3-ubuntu22.04
````

The arch specific images could be pulled via
```
podman pull finkandreas/spack:0.20.3-ubuntu22.04-x86_64
podman pull finkandreas/spack:0.20.3-ubuntu22.04-aarch64
```

This change will make sure that we are backwards compatible, i.e. old pipelines will continue to run and pick up the x86_64 architecture, while pipelines on GH will work too with the same image name as base container starting point.

We cannot have Rocm images because there are no base images for arm64.

2024-02-07 14:48 UTC, finkandreas commented
One thing I do not like is that we have in the build script and the manifest creation script the same loop variables and must be maintained together. I see in the future that this might create some bugs on our side.
I am open for suggestions how this could be worked around. Separate file with the possible variable values and source the file?

2024-02-09 14:46 UTC, rjanalik commented
Yeah, I also don't like this. I think we should move the variables to a file as you suggest, e.g., config.json.

2024-02-09 19:44 UTC, rjanalik requested changes

2024-02-09 19:44 UTC, rjanalik commented on build_and_push.sh
> +        if [[ "$1" == "image" ]] ; then
What about something like this?
```suggestion
        if [[ "$COMMAND" == "image" ]] ; then
```
And somewhere above
```
COMMAND=$1
```

2024-02-09 19:44 UTC, rjanalik commented on build_and_push.sh
> +        elif [[ "$1" == "manifest" ]] ; then
The same here
And 3x below

2024-02-09 19:45 UTC, rjanalik approved these changes

2024-02-09 19:49 UTC, merged