Add spack repo feature to the helper script
eth-cscs/ci-ext-base-containers pull request #7
Opened 2024-04-04 09:50 UTC by rjanalik

2024-04-04 09:53 UTC, rjanalik commented
What about renaming `--with-repo` to `--add-repo`?

2024-04-18 07:09 UTC, finkandreas requested changes
in general it is fine. Not sure if we want to support both syntaxes, `--add-repo=my_repo` and `--add-repo my_repo`. The former right now would not work. I guess you could make it work like
```bash
case $1 in
  --add-repo* )
    ...
    shift
    if [[ $1 == "--add-repo" ]] ; then
      shift
    fi
esac
```

However I am also fine with enforcing supporting only the latter syntax and disallowing the form `--some-arg=some-value` (this is more of a decision we need to make and stick to that decision)

2024-04-18 07:09 UTC, finkandreas commented on bin/spack-install-helper-10-preprocessing
> +            SPACK_REPO_LIST+=($2)
probably never happening, but if someone ever comes up with weir whitespace directories, we would nee `"$2"`, i.e. quote the argument

2024-04-18 07:09 UTC, finkandreas commented on bin/spack-install-helper-20-configure-environment
> +    spack repo add ${repo}
same as above, it needs quotes, i.e. `"${repo}"`

2024-04-18 07:16 UTC, finkandreas requested changes

2024-04-18 07:16 UTC, finkandreas commented on bin/spack-install-helper-20-configure-environment
> +for repo in ${SPACK_REPO_LIST[@]}
Also here we need quotes, i.e. `"${SPACK_REPO_LIST[@]}`

2024-04-18 11:39 UTC, finkandreas approved these changes
lgtm

2024-04-18 11:43 UTC, merged